// https://mobile-legends.fandom.com/wiki/List_of_heroes

type HeroMeta = { name: string; icon: string };

export const heroes = {
	aamon: { name: "Эймон", icon: "/heroes_icons/aamon.webp" },
	akai: { name: "Акай", icon: "/heroes_icons/akai.webp" },
	aldous: { name: "Алдос", icon: "/heroes_icons/aldous.webp" },
	alice: { name: "Алиса", icon: "/heroes_icons/alice.webp" },
	alpha: { name: "Альфа", icon: "/heroes_icons/alpha.webp" },
	alucard: { name: "Алукард", icon: "/heroes_icons/alucard.webp" },
	angela: { name: "Ангела", icon: "/heroes_icons/angela.webp" },
	argus: { name: "Аргус", icon: "/heroes_icons/argus.webp" },
	arlott: { name: "Арлотт", icon: "/heroes_icons/arlott.webp" },
	atlas: { name: "Атлас", icon: "/heroes_icons/atlas.webp" },
	aulus: { name: "Аулус", icon: "/heroes_icons/aulus.webp" },
	aurora: { name: "Аврора", icon: "/heroes_icons/aurora.webp" },
	badang: { name: "Баданг", icon: "/heroes_icons/badang.webp" },
	balmond: { name: "Бальмонд", icon: "/heroes_icons/balmond.webp" },
	bane: { name: "Бейн", icon: "/heroes_icons/bane.webp" },
	barats: { name: "Бартс", icon: "/heroes_icons/barats.webp" },
	baxia: { name: "Баксий", icon: "/heroes_icons/baxia.webp" },
	beatrix: { name: "Беатрис", icon: "/heroes_icons/beatrix.webp" },
	belerick: { name: "Белерик", icon: "/heroes_icons/beleric.webp" },
	benedetta: { name: "Бенедетта", icon: "/heroes_icons/benedetta.webp" },
	brody: { name: "Броуди", icon: "/heroes_icons/brody.webp" },
	bruno: { name: "Бруно", icon: "/heroes_icons/bruno.webp" },
	carmilla: { name: "Кармилла", icon: "/heroes_icons/carmlla.webp" },
	cecillion: { name: "Сисилион", icon: "/heroes_icons/cecillion.webp" },
	change: { name: "Чан Э", icon: "/heroes_icons/change.webp" },
	chip: { name: "Чип", icon: "/heroes_icons/chip.webp" },
	chou: { name: "Чу", icon: "/heroes_icons/chou.webp" },
	cici: { name: "Чичи", icon: "/heroes_icons/cici.webp" },
	claude: { name: "Клауд", icon: "/heroes_icons/claude.webp" },
	clint: { name: "Клинт", icon: "/heroes_icons/clint.webp" },
	cyclops: { name: "Циклоп", icon: "/heroes_icons/cyclops.webp" },
	diggie: { name: "Дигги", icon: "/heroes_icons/diggie.webp" },
	dyrroth: { name: "Дариус", icon: "/heroes_icons/dyrroth.webp" },
	edith: { name: "Эдит", icon: "/heroes_icons/edith.webp" },
	esmeralda: { name: "Эсмеральда", icon: "/heroes_icons/esmeralda.webp" },
	estes: { name: "Эстес", icon: "/heroes_icons/estes.webp" },
	fanny: { name: "Фанни", icon: "/heroes_icons/fanny.webp" },
	faramis: { name: "Фарамис", icon: "/heroes_icons/faramis.webp" },
	floryn: { name: "Флорин", icon: "/heroes_icons/floryn.webp" },
	franco: { name: "Франко", icon: "/heroes_icons/franco.webp" },
	fredrinn: { name: "Фредрин", icon: "/heroes_icons/fredrinn.webp" },
	freya: { name: "Фрейя", icon: "/heroes_icons/freya.webp" },
	gatotkaca: { name: "Гатоткача", icon: "/heroes_icons/gatotkaca.webp" },
	gloo: { name: "Глу", icon: "/heroes_icons/gloo.webp" },
	gord: { name: "Горд", icon: "/heroes_icons/gord.webp" },
	granger: { name: "Грейнджер", icon: "/heroes_icons/granger.webp" },
	grock: { name: "Грок", icon: "/heroes_icons/grock.webp" },
	guinevere: { name: "Гвиневра", icon: "/heroes_icons/gunevere.webp" },
	gusion: { name: "Госсен", icon: "/heroes_icons/gusion.webp" },
	hanabi: { name: "Ханаби", icon: "/heroes_icons/hanabi.webp" },
	hanzo: { name: "Ханзо", icon: "/heroes_icons/hanzo.webp" },
	harith: { name: "Харит", icon: "/heroes_icons/harith.webp" },
	harley: { name: "Харли", icon: "/heroes_icons/harley.webp" },
	hayabusa: { name: "Хаябуса", icon: "/heroes_icons/hayabusa.webp" },
	helcurt: { name: "Хелкарт", icon: "/heroes_icons/helcurt.webp" },
	hilda: { name: "Хильда", icon: "/heroes_icons/hilda.webp" },
	hylos: { name: "Хилос", icon: "/heroes_icons/hylos.webp" },
	irithel: { name: "Иритель", icon: "/heroes_icons/irithel.webp" },
	ixia: { name: "Иксия", icon: "/heroes_icons/ixia.webp" },
	jawhead: { name: "Кусака", icon: "/heroes_icons/jawhead.webp" },
	johnson: { name: "Джонсон", icon: "/heroes_icons/johnson.webp" },
	joy: { name: "Джой", icon: "/heroes_icons/joy.webp" },
	julian: { name: "Джулиан", icon: "/heroes_icons/julian.webp" },
	kadita: { name: "Кадита", icon: "/heroes_icons/kadita.webp" },
	kagura: { name: "Кагура", icon: "/heroes_icons/kagura.webp" },
	kaja: { name: "Кайя", icon: "/heroes_icons/kaja.webp" },
	kalea: { name: "Калея", icon: "/heroes_icons/kalea.webp" },
	karina: { name: "Карина", icon: "/heroes_icons/karina.webp" },
	karrie: { name: "Керри", icon: "/heroes_icons/kerrie.webp" },
	khaleed: { name: "Халид", icon: "/heroes_icons/khaleed.webp" },
	khufra: { name: "Хуфра", icon: "/heroes_icons/khufra.webp" },
	kimmy: { name: "Кимми", icon: "/heroes_icons/kimmy.webp" },
	lancelot: { name: "Ланселот", icon: "/heroes_icons/lancelot.webp" },
	lapuLapu: { name: "Лапу-Лапу", icon: "/heroes_icons/lapu-lapu.webp" },
	layla: { name: "Лейла", icon: "/heroes_icons/layla.webp" },
	leomord: { name: "Леоморд", icon: "/heroes_icons/leomord.webp" },
	lesley: { name: "Лесли", icon: "/heroes_icons/lesley.webp" },
	ling: { name: "Линг", icon: "/heroes_icons/ling.webp" },
	lolita: { name: "Лолита", icon: "/heroes_icons/lolita.webp" },
	lukas: { name: "Лукас", icon: "/heroes_icons/lukas.webp" },
	lunox: { name: "Люнокс", icon: "/heroes_icons/lunox.webp" },
	luoyi: { name: "Ло Йи", icon: "/heroes_icons/luoyi.webp" },
	lylia: { name: "Лилия", icon: "/heroes_icons/lylia.webp" },
	marcel: { name: "Марсель", icon: "/heroes_icons/marcel.webp" },
	martis: { name: "Мартис", icon: "/heroes_icons/martis.webp" },
	masha: { name: "Маша", icon: "/heroes_icons/masha.webp" },
	mathilda: { name: "Матильда", icon: "/heroes_icons/mathilda.webp" },
	melissa: { name: "Мелисса", icon: "/heroes_icons/melissa.webp" },
	minotaur: { name: "Минотавр", icon: "/heroes_icons/minotaur.webp" },
	minsitthar: { name: "Минситтар", icon: "/heroes_icons/minsstthar.webp" },
	miya: { name: "Мия", icon: "/heroes_icons/miya.webp" },
	moskov: { name: "Москов", icon: "/heroes_icons/moskov.webp" },
	nana: { name: "Нана", icon: "/heroes_icons/nana.webp" },
	natalia: { name: "Наталья", icon: "/heroes_icons/natalia.webp" },
	natan: { name: "Натан", icon: "/heroes_icons/natan.webp" },
	nolan: { name: "Нолан", icon: "/heroes_icons/nolan.webp" },
	novaria: { name: "Новария", icon: "/heroes_icons/novaria.webp" },
	odette: { name: "Одетта", icon: "/heroes_icons/odette.webp" },
	paquito: { name: "Пакито", icon: "/heroes_icons/paquito.webp" },
	pharsa: { name: "Фаша", icon: "/heroes_icons/pharsa.webp" },
	phoveus: { name: "Фовиус", icon: "/heroes_icons/phoveus.webp" },
	popolAndKupa: {
		name: "Пополь и Купа",
		icon: "/heroes_icons/popolandkupa.webp",
	},
	rafaela: { name: "Рафаэль", icon: "/heroes_icons/rafaela.webp" },
	roger: { name: "Роджер", icon: "/heroes_icons/roger.webp" },
	ruby: { name: "Руби", icon: "/heroes_icons/ruby.webp" },
	saber: { name: "Сабер", icon: "/heroes_icons/saber.webp" },
	selena: { name: "Селена", icon: "/heroes_icons/selena.webp" },
	silvanna: { name: "Сильванна", icon: "/heroes_icons/silvanna.webp" },
	sora: { name: "Сора", icon: "/heroes_icons/sora.webp" },
	sun: { name: "Сан", icon: "/heroes_icons/sun.webp" },
	suyou: { name: "Су Ё", icon: "/heroes_icons/suyou.webp" },
	terizla: { name: "Теризла", icon: "/heroes_icons/terizla.webp" },
	thamuz: { name: "Тамуз", icon: "/heroes_icons/thamuz.webp" },
	tigreal: { name: "Тигрил", icon: "/heroes_icons/tigreal.webp" },
	uranus: { name: "Уранус", icon: "/heroes_icons/uranus.webp" },
	vale: { name: "Вейл", icon: "/heroes_icons/vale.webp" },
	valentina: { name: "Валентина", icon: "/heroes_icons/valentina.webp" },
	valir: { name: "Валир", icon: "/heroes_icons/valir.webp" },
	vexana: { name: "Вексана", icon: "/heroes_icons/vexana.webp" },
	wanwan: { name: "Ван Ван", icon: "/heroes_icons/wanwan.webp" },
	xavier: { name: "Ксавьер", icon: "/heroes_icons/xavier.webp" },
	xBorg: { name: "Икс-Борг", icon: "/heroes_icons/xborg.webp" },
	yin: { name: "Инь", icon: "/heroes_icons/yin.webp" },
	yiSunShin: { name: "Ли Сун Син", icon: "/heroes_icons/yi-sun-shin.webp" },
	yuZhong: { name: "Чонг", icon: "/heroes_icons/yozhong.webp" },
	zetian: { name: "Цзэтянь", icon: "/heroes_icons/zetian.webp" },
	zhask: { name: "Заск", icon: "/heroes_icons/zhask.webp" },
	zhuxin: { name: "Чжу Синь", icon: "/heroes_icons/zhuxin.webp" },
	zilong: { name: "Зилонг", icon: "/heroes_icons/zilong.webp" },
	eudora: { name: "Эйдора", icon: "/heroes_icons/eudora.webp" },
	obsidia: { name: "Обсидия", icon: "/heroes_icons/obsidia.webp" },
} as const satisfies Record<string, HeroMeta>;

export type HeroId = keyof typeof heroes;
export type HeroesNameType = (typeof heroes)[HeroId]["name"];
